groups:
- name: alert-rules                               #告警的分组，后续告警优化时，可通过分组做优化配置
  rules:
  - alert: InstanceStatus                        #告警规则名称
    expr: up{job="node"} == 0    #1是服务正常 ，0服务挂了
    for: 10s                                             #评估等待10s，等待期间报警状态为pending
    labels:                                               #此标签可用于match之后的通知操作
      severity: 'critical'   
    annotations:                                      #描述告警信息
      description: 服务器 已宕机
      summary: 服务器 运行状态
